# Conexión dinámica con variables de Railway
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQL_DATABASE}?serverTimezone=UTC
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
# Cambiado a MySQLDialect para evitar errores de deprecación
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Cambiado a 'update' para que cree tus tablas (Producto, Usuario, etc.)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Puerto dinámico
server.port=${PORT:8080}